/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aaar.juegosmesa.gui.dblocation;

import aaar.juegosmesa.gui.menu.MainMenuGUI;
import aaar.juegosmesa.helpers.PathHelperFunctions;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author debi12
 */
public class JDatabaseFilePathFrame
        extends javax.swing.JFrame
{
    private String dbFilePath = "";
    /**
     * Creates new form JDatabaseLocationFrame
     */
    public JDatabaseFilePathFrame() {
        initComponents();
        jDatabaseFilePathTextField.getDocument().addDocumentListener(new DocumentListener() {
            private void updateConfirmButton() {
                String path = jDatabaseFilePathTextField.getText();
                jCreateDatabaseButton.setEnabled(
                        PathHelperFunctions.isValidPath(path)
                );
                dbFilePath = path;
            }

            @Override
            public void insertUpdate(DocumentEvent de) {
                updateConfirmButton();
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                updateConfirmButton();
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
                updateConfirmButton();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jDatabaseFileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDatabaseFilePathTextField = new javax.swing.JFormattedTextField();
        jBrowseFileButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCancelButton = new javax.swing.JButton();
        jCreateDatabaseButton = new javax.swing.JButton();

        jDatabaseFileChooser.setApproveButtonText("");
        jDatabaseFileChooser.setCurrentDirectory(null);
        jDatabaseFileChooser.setDialogTitle("");
        jDatabaseFileChooser.setSelectedFiles(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0};
        layout.rowHeights = new int[] {0};
        getContentPane().setLayout(layout);

        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Indique la ruta donde desea almacenar la base de datos.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jDatabaseFilePathTextField, gridBagConstraints);

        jBrowseFileButton.setText("Navega...");
        jBrowseFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrowseFileButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(jBrowseFileButton, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 15, 0));

        jCancelButton.setText("Cancelar");
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(jCancelButton);

        jCreateDatabaseButton.setText("Crear base de datos");
        jCreateDatabaseButton.setEnabled(false);
        jCreateDatabaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateDatabaseButtonActionPerformed(evt);
            }
        });
        jPanel2.add(jCreateDatabaseButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 0);
        jPanel1.add(jPanel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCreateDatabaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateDatabaseButtonActionPerformed
        String dbFilePathStr = dbFilePath;
        try {
            // create db file
            String initialContent = "";
            BufferedWriter writer = new BufferedWriter(
                    new FileWriter(dbFilePathStr)
            );
            writer.write(initialContent);
            writer.close();
            
            // write to user prefs
            String prefsContent = dbFilePathStr + "\n";
            BufferedWriter prefsWriter = new BufferedWriter(
                    new FileWriter(".userPrefs")
            );
            prefsWriter.write(prefsContent);
            prefsWriter.close();
        } catch (Exception e) {
            System.err.println(e.getMessage());
        } finally {
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new MainMenuGUI().setVisible(true);
                }
            });
            dispose();
        }
    }//GEN-LAST:event_jCreateDatabaseButtonActionPerformed

    private void jBrowseFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrowseFileButtonActionPerformed
        int option = jDatabaseFileChooser.showSaveDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            String dbFilePath = jDatabaseFileChooser.getSelectedFile().getAbsolutePath();
            jDatabaseFilePathTextField.setText(dbFilePath);
        }
    }//GEN-LAST:event_jBrowseFileButtonActionPerformed

    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_jCancelButtonActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBrowseFileButton;
    private javax.swing.JButton jCancelButton;
    private javax.swing.JButton jCreateDatabaseButton;
    private javax.swing.JFileChooser jDatabaseFileChooser;
    private javax.swing.JFormattedTextField jDatabaseFilePathTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
